version: '3'
services:
  mysql8:
    container_name: mysql8-u01
    environment:
      MYSQL_ROOT_PASSWORD: "qwe@123"
    image: mysql:8.0.23
    restart: always
    ports:
      - "33306:3306"
    volumes:
      - /d/docker/mysql8/conf:/etc/mysql/conf.d
      - /d/docker/mysql8/logs:/var/log/mysql
      - /d/docker/mysql8/data:/var/lib/mysql
      - /d/docker/mysql8/init:/docker-entrypoint-initdb.d